cmd/server/main.go

Work towards: https://github.com/onflow/flow-evm-gateway/issues/20
- The indexer now connects to `127.0.0.1:3569` (emulator Access API)
- The indexer now subscribes to EVM related events (`flow.evm.BlockExecuted` & `flow.evm.TransactionExecuted`)
______

Use Emulator gRPC host for default access URL and update event types to EVM

---

api/api.go
api/api_test.go
api/fixtures/eth_json_rpc_requests.json
api/fixtures/eth_json_rpc_responses.json

Closes: https://github.com/onflow/flow-evm-gateway/issues/8
Updates the method interfaces to match the ones expected from JSON-RPC specification, and adds tests to cover the expected behavior.
______

Add proper method interfaces for unsupported API methods

---

api/api.go
api/api_test.go
api/cadence/transactions/evm_run.cdc
api/fixtures/eth_json_rpc_requests.json
api/fixtures/eth_json_rpc_responses.json
api/server_test.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/2
Functionality to send raw EVM transactions.
______

Implement the `eth_sendRawTransaction` JSON-RPC endpoint

---

models/block.go
models/block_test.go
models/transaction.go
models/transaction_test.go

Closes: #16 
This PR adds the decoding of event data into evm typed data that will be used for storage and querying. 
______

[Indexer] Decoding of event values

---

api/api.go
api/api_test.go
api/config.go
api/server_test.go
cmd/server/main.go

Work towards: https://github.com/onflow/flow-evm-gateway/issues/2
Allow configuration of value returned by the `eth_gasPrice` JSON-RPC endpoint.
______

Make value returned by `eth_gasPrice` configurable

---

Makefile
api/cadence/transactions/create_bridged_account.cdc
flow.json

- Adds a `make` recipe to setup the service account with a COA
- Adds a `make` recipe to start the emulator with the `--evm-enabled` feature flag
- Adds a `make` recipe to start the Flow EVM Gateway
______

Setup improvements for running the Flow EVM Gateway

---

.github/workflows/deploy.yml
Dockerfile
api/server_test.go
cmd/server/main.go
scripts/run.sh

Closes: #???
Dockerfile for a build to deploy
______

Docker file

---

api/config.go
cmd/server/main.go
go.mod
go.sum

- Temporary workaround to fix the build errors. Taken from: https://github.com/onflow/flow-cli/pull/1366#discussion_r1473429002
- Also adds CLI flags for `host`, `port` and `network` (automatically chooses the Access URL)
```shell
go run ./cmd/server/main.go --host="localhost" --port=8545 --network="emulator"
```
______

Fix build errors

---

api/api.go
api/net_api.go
api/server.go
api/server_test.go
api/web3_api.go

Adds the following JSON-RPC endpoints:
- `net_listening`
- `net_peerCount`
- `net_version`
- `web3_clientVersion`
- `web3_sha3`
`web3.js` makes use of some of the above.
Documentation with instructions on running the gateway locally as added, as well as a list of ready JSON-RPC calls to executed.
______

Add `net` and `web3` namespaces

---

api/server.go
go.mod
go.sum

Set allowed origins to `"*"`, meaning all.
This will allow tools such as Remix and MetaMask to properly connect to the JSON-RPC server.
______

Add CORS handler for JSON-RPC over HTTP

---

api/api.go
api/eoa_test_account.go
integration/e2e_test.go
integration/helpers.go
services/requester/cadence/estimate_gas.cdc
services/requester/requester.go

Residual from: https://github.com/onflow/flow-evm-gateway/issues/9
Utilizes the new interface of `EVM.run` inside a Cadence script, to run an EVM transaction in order to retrieve the gas consumption and any possible failures. No state change occurs.
______

Implement the `eth_estimateGas` JSON-RPC endpoint

---

models/block.go
models/block_test.go
models/transaction.go
models/transaction_test.go

Reverts onflow/flow-evm-gateway#40Closes: https://github.com/onflow/flow-evm-gateway/issues/16
This is a revert of https://github.com/onflow/flow-evm-gateway/pull/36 due to an unintended merge.
The original PR implemented decoding of Flow EVM events into models we defined in evm-gateway.

Revert "[Indexer] Decoding of event values"

---

api/api.go
integration/web3js/index.js

Make `gas` argument in `eth_estimateGas` endpoint optional.
______

Make `gas` argument in `eth_estimateGas` endpoint optional.

---

README.md

To help integrators and developers am adding the supported methods, and those we plan to support, for added clarity when they are testing

Add eth namespace methods for specificity

---

api/api.go
api/server.go
config/config.go
go.mod
integration/e2e_test.go
integration/helpers.go
services/requester/requester.go

General improvements to the code, addressing some todos, removing non-relevant todos, concurrently get data from network, improve balance conversions...

General improvements and tech-debt

---

integration/e2e_test.go
integration/helpers.go
services/requester/cadence/call.cdc
services/requester/cadence/estimate_gas.cdc
services/requester/cadence/get_balance.cdc
services/requester/cadence/get_nonce.cdc
services/requester/cadence/run.cdc
services/requester/requester.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/123
Update Cadence scripts & transactions to accept EVM tx & data as hex-encoded strings instead of Cadence byte arrays. This is far more effiecient with the current JSON-CDC encoder.
______

Optimize format for EVM txs & data

---

api/server.go
services/requester/requester.go

Show JSON in logs as JSON and not string. Also add sender address to the log output when sending new transaction, so we can know who sent it.

Log improvements

---

go.mod
storage/pebble/accounts.go
storage/pebble/storage.go

Closes: #119 
This PR adds caching on the storage layer. We use 2 queue caching that separately tracks common and recent.  
______

Database caching

---

README.md
bootstrap/bootstrap.go
config/config.go
integration/e2e_test.go
integration/helpers.go
storage/pebble/blocks.go
storage/pebble/storage_test.go

- Updates README with proper instructions on running the EVM Gateway with a local Emulator
- Updates the bootstrap logic to work with live networks as well as a local Emulator
- Updates the E2E tests
______

Update bootstrap logic and README instructions to work with a local Emulator

---

api/api.go
api/sign_transaction.go
services/requester/cadence/call.cdc
services/requester/requester.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/113
This will allow us to simulate contract deployments by using the `eth_call` JSON-RPC endpoint. Later on, we can consolidate the logic for `eth_estimateGas` and `eth_call`, as they are actually quite similar in nature.
______

Support empty `To` address in `eth_call` endpoint

---

api/api.go
api/models.go
integration/e2e_test.go
integration/helpers.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/112
Add support for returning the full transaction info for `eth_getBlockByNumber` and `eth_getBlockByHash` endpoints
______

Add support for returning full transactions

---

services/requester/cadence/run.cdc

Closes: https://github.com/onflow/flow-evm-gateway/issues/83
Change `assert` condition on `run.cdc` transaction, so that we allow block formation for EVM transactions with validation errors. This way, the Gateway will receive an `evm.TransactionExecuted` event, with the `VMError` field populated with the corresponding error.
______

Properly handle tx results from `EVM.run`

---

api/api.go
api/sign_transaction.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/161
The EOA test account used for signing the transaction that encapsulates the user's `TransactionArgs`, does not have any funds. This means that if `GasPrice` is greater than 0, we return:
```json
{
"jsonrpc": "2.0",
"id": 1,
"error": {
"code": -32000,
"message": "insufficient funds for gas * price + value"
}
}
```
By setting this argument to `0`, we now return the intrinsic gas, which is `0xcf08` (or `53000` in decimal). The gas is mainly affected by the length of the `data` / `input` field value.
______

Set `GasPrice` to `0` for gas estimation tx

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Update flow go to `v0.35.4-crescendo-preview.20-evm-fix3` which contains fixed Block decoder.

Update Flow Go

---

services/requester/requester.go
tests/web3js/eth_deploy_contract_and_interact_test.js

There was a strange issue reported, when a tx was attempting to update a contract's field, to its current value.
The `eth_estimateGas` would return a gas estimation of `28380`, but when sending the tx with this value as the gas limit, then it would error out with an `errorCode` of `301, which is `out of gas`.
The problem arises from this check: https://github.com/onflow/go-ethereum/blob/master/core/vm/operations_acl.go#L29-L32.
In this PR, we update the `eth_estimateGas` endpoint to add [SstoreSentryGasEIP2200](https://github.com/onflow/go-ethereum/blob/fb8de1862fe8db58b76aebf13f8f1183e6c67608/params/protocol_params.go#L61), to the gas consumed returned by `EVM.dryRun`. Note that the gas value of `SstoreSentryGasEIP2200` is not actually consumed, but it has to be available._____
For …

Always add a buffer gas of `SstoreSentryGasEIP2200` for `eth_estimateGas` endpoint

---

api/api.go
bootstrap/bootstrap.go
services/requester/requester.go
storage/pebble/storage.go

EVM requester now takes in EVM height instead of Cadence height, since this was causing issues in an edge case where we wanted to get balance at the latest EVM height, but we provided that specific EVM height instead of using "latest" as the special value when interacting with API, this caused the EVM height to be mapped to Cadence height which might not be recent (in case there were no EVM events for a while), this could cause EN to have pruned the state at that Cadence height.
This now replaces EVM height with latest if it equals the latest value.
______

EVM Requester accept EVM height

---

api/api.go
services/requester/requester.go

Don't log known out-of-range error as it spams the error logs. This is a user error and we shouldn't log it as a system error. In the future introduce user error type which would wrap similar errors.
______

Remove logging of user errors

---

api/server.go
bootstrap/bootstrap.go
config/config.go

Allow defining header value used for determining the client source IP. This is useful when the EVM GW is behind a proxy that sets the source IP in a header. 
Also add this source IP to logs so we can validate how this behaves on a deployment.
______

Overwrite source address with logging

---

api/api.go
emulator/remote_state_test.go
services/requester/remote_state.go
services/requester/remote_state_test.go
services/requester/requester.go

Relies on: #362 
Related: #351 
This builds on top of #362 and exposes the `eth_getStorageAt` API needed for inspecting the account storage.
Example:
```
curl -XPOST 'localhost:3000' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0", "method": "eth_getStorageAt", "params": ["0x07C2006580b42cB35Bc4583fEB4904626CcdfA60", "0x0", "latest"], "id": 1}'
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000064"}
```
______

Get storage at API

---

api/api.go

Bugfix optional value being used in logs producing nil pointer exception.

Bugfix nil value in log

---

storage/pebble/receipts.go

Add a workaround for decoding a single stored bloom. We need to investigate why a single bloom is getting stored in the first place.

Single bloom decoding

---

api/server.go
metrics/collector.go
metrics/nop.go
tests/helpers.go

Closes: #384 
This PR implements reporting panics as well as improves the response handler. Unfortunatelly until we implement our own server this is the best approach we can take at handling panics as they are recovered inside the go-ethereum server implementation.
______

API panic handler metric

---

bootstrap/bootstrap.go
services/ingestion/engine.go
services/ingestion/engine_test.go
services/replayer/blocks_provider.go
services/replayer/blocks_provider_test.go
storage/mocks/mocks.go

Closes: #630
Closes: #631 
- Adds two new types that implement the `BlockSnapshotProvider` & `BlockSnapshot` interfaces
- Injects the `BlocksProvider` type to the Event Ingestion Engine, with a default `callTracer`
- Keeps track of `EVM` blocks that are received
______

Implement `BlockSnapshotProvider` & `BlockSnapshot` interfaces

---

api/api.go
services/requester/requester.go

Extracted from https://github.com/onflow/flow-evm-gateway/pull/635
I think the API should translate the special heights to actual heights before forwarding to the requester.
______

Special evm height handling

---

api/api.go
services/requester/requester.go

Changed evm height in requester to uint since the requester doesn't need to know about special evm heights
______

Changed evm height in requester to uint

---

models/events.go
models/events_test.go
services/ingestion/event_subscriber.go

The new back-fill mechanism, that uses plain-old gRPC APIs, such as `GetEventsForHeightRange`, needs to handle the case where an `EVM.BlockExecuted` event might be missing. This is a special case for `mainnet`, where it occurred due to the system chunk transaction failure. 
______

Handle missing EVM block event in backfill

---

storage/pebble/blocks.go

The EVM block at which `PrevRandao` was introduced, needs some special handling for setting the `Hash` & `ParentBlockHash` fields, as the addition of the `PrevRandao` field caused the hash calculation to change.
______

Fix wrong block hash value for the 1st EVM block with `PrevRandao`

---

services/ingestion/engine.go
services/ingestion/engine_test.go
storage/index.go

I split up the function a bit, to hopefully make it a bit clearer. 
I also noticed that there was a bug where if `events.Empty()` then the batch containing the new cadence height never got committed. This should be fixed.
______

Refactor re-execution

---

models/events.go
models/events_test.go
services/ingestion/engine_test.go
services/ingestion/event_subscriber.go

Handle ingestion of missing `EVM.BlockExecuted` event in backfill process

---

README.md
api/api.go
api/debug.go
tests/e2e_web3js_test.go
tests/web3js/debug_util_test.js

Added `debug_flowHeight` API endpoint so you can get the flow height at a given EVM block
______

Add debug_flowHeight API endpoint

---

bootstrap/bootstrap.go
cmd/run/cmd.go
tests/helpers.go
tests/integration_test.go

Progressively refactoring startup/shutdown to switch to node builder.
This is part 1, with some cleanup to the CMD to make it cleared whats going on.
Note: I did not like the design where `bootstrap.Run` closed a write channel that was passed in, so I refactored that into a `ready()` function which is also more in line with components in flow-go
______

Cleanup run cmd

---

api/api.go
bootstrap/bootstrap.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/644
______

Fix race for `startingBlock` field of `eth_syncing` endpoint

---

api/api.go
api/debug.go
api/net.go
api/pull.go
api/pull_test.go
api/server.go
api/stream.go
api/wallet.go
bootstrap/bootstrap.go
cmd/run/cmd.go
services/requester/requester.go
tests/helpers.go
tests/integration_test.go

IMO its safer to use an instance so we don't get strange behavior if something accidentally changes the config. It also doesn't need to be a reference since it is not expected to be modified.
______

Use instance of config instead of reference

---

api/utils.go
services/requester/requester.go
tests/web3js/build_evm_state_test.js
tests/web3js/debug_traces_test.js
tests/web3js/eth_deploy_contract_and_interact_test.js

Between the binary search iterations, we should check if the tx failed with any VM error, and not just `ExecutionErrCodeOutOfGas`.
In many cases, a tx that failed with `out of gas` will have a `ExecutionErrCodeExecutionReverted` error code. One such case is Solidity's `staticcall`, which can fail with an `out of gas` error, but it doesn't bubble up the specific error, and in turn the top-level call will fail with a generic `execution reverted` error.
______

Fix logical error in `eth_estimateGas` endpoint

---

api/api.go
storage/index_test.go
storage/pebble/receipts.go
tests/e2e_web3js_test.go
tests/web3js/eth_logs_filtering_test.js

Closes: https://github.com/onflow/flow-evm-gateway/issues/695
We also return an empty `Receipts` array, for blocks with no transactions, as this is normal.
______
- [] Targeted PR against `master` branch

Return empty `Logs` array when block is empty

---

api/debug.go
bootstrap/bootstrap.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/703
______

Apply rate-limit on tracing endpoints

---

bootstrap/bootstrap.go

The account keys used on the testnet account (https://testnet.flowscan.io/account/8b9a5d24cb3b0164/keys), do not all have the same public key, so we need to guard against this case.
Related error: https://testnet.flowscan.io/tx/998fbf8c04d08c09ea99d2203fe5c4b04d3e5de3c56fc71ce304954591461703
______

Skip account keys with different publick key than the configured signer

---

api/debug.go
services/evm/executor.go

Closes: https://github.com/onflow/flow-evm-gateway/issues/708
Also improved the detection of default tracer config, by disregarding whitespaces.
______

Use current block data when constructing `BlockContext` for trace generation

---

bootstrap/bootstrap.go
cmd/run/cmd.go
config/config.go
services/ingestion/block_tracking_subscriber.go
services/ingestion/sealing_verifier.go
storage/pebble/db.go
storage/pebble/events_hash.go
storage/pebble/keys.go

Closes: #???
This PR adds a new subsystem `SealingVerifier` that tracks the unsealed events processed by the ingestion engine, and compares them against the events that were eventually sealed. If there is a mismatch, the node crashes with an error.
This adds a layer of protection in the event that there was an execution fork, and the node ingested data from the unsealed fork. In this case, the node will stop reploying to requests over it's API until it has been rolled back
______

add system to verify soft finality events were eventually sealed

---

api/debug.go
go.mod
go.sum
tests/go.mod
tests/go.sum
tests/web3js/contract_call_overrides_test.js

Depends on: https://github.com/onflow/go-ethereum/pull/9
Updates to `flow-go` version using `go-ethereum@v1.14.9` and fixes some minor breaking changes.
______

Update to `flow-go` with `go-ethereum@v1.14.9`

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/10
Updates to `flow-go` version using `go-ethereum@v1.14.10` .
______

Update to `flow-go` with `go-ethereum@v1.14.10`

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/11
Updates to `flow-go` version using `go-ethereum@v1.14.11` .
______

Update to `flow-go` with `go-ethereum@v1.14.11`

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/13
Updates to `flow-go` version using `go-ethereum@v1.14.13` .
______

Update to `flow-go` with `go-ethereum@v1.14.13`

---

go.mod
go.sum
models/transaction_test.go
services/requester/requester.go
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/15
Updates to `flow-go` version using `go-ethereum@v1.15.1` .
______

Update to `flow-go` with `go-ethereum@v1.15.1`

---

api/api.go
api/stream.go
go.mod
go.sum
models/receipt.go
models/transaction.go
services/logs/filter_test.go
tests/e2e_web3js_test.go
tests/go.mod
tests/go.sum
tests/web3js/eth_batch_tx_logs_test.js

Depends on: https://github.com/onflow/go-ethereum/pull/16
Updates to `flow-go` version using `go-ethereum@v1.15.2` .
______

Update to `flow-go` with `go-ethereum@v1.15.2`

---

go.mod
go.sum
models/transaction_test.go
tests/go.mod
tests/go.sum
tests/web3js/build_evm_state_test.js
tests/web3js/debug_traces_test.js
tests/web3js/eth_deploy_contract_and_interact_test.js

Bump `onflow/flow-go` version with EVM Pectra hard-fork enabled

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/18
Updates to `flow-go` version using `go-ethereum@v1.15.4` .
______

Update to `flow-go` with `go-ethereum@v1.15.4`

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Depends on: https://github.com/onflow/go-ethereum/pull/19
Updates to `flow-go` version using `go-ethereum@v1.15.5` .
______

Update to `flow-go` with `go-ethereum@v1.15.5`

---

README.md
cmd/run/cmd.go
config/config.go
services/requester/requester.go
tests/helpers.go
tests/integration_test.go

Backports: https://github.com/onflow/flow-evm-gateway/pull/810
Backports PR to add `enforce-gas-price` flag to PoC branch

Add flag to disable enforcing the minimum gas price

---

eth/types/types.go
models/transaction.go
tests/web3js/eth_eip_7702_contract_write_test.js
tests/web3js/eth_eip_7702_sending_transactions_test.js

Back-port https://github.com/onflow/flow-evm-gateway/pull/821
As described in the specification: https://eip7702.io/#specification, the new `SetCodeTx` type, has an authorization list:
```bash
authorization_list = [[chain_id, address, nonce, y_parity, r, s], ...]
```
Example:
```bash
{
address: '0x313af46a48eeb56d200fae0edb741628255d379f',
chainId: 646,
nonce: 4,
r: '0xf4bc19cca28390f3628cfcda9076a8744b77cc87fa4f7745efa83b7a06cc3514',
s: '0x1d736fecc68ee92ab6fd805d91a3e3dbf27097d3578561402d7105eeeee00bb7',
yParity: 0
}
```
We need to include this information in the result of `eth_getTransactionByHash` JSON-RPC endpoint.
______

Return authorization list for `SetCodeTx` type

---

cmd/run/cmd.go
config/config.go
services/requester/batch_tx_pool.go

Mainly changes from https://github.com/onflow/flow-evm-gateway/pull/852 .
______

Back-port changes from `main` to soft-finality
