- api/api.go
- api/api_test.go
- api/fixtures/eth_json_rpc_requests.json
- api/fixtures/eth_json_rpc_responses.json
- cmd/server/main.go
- storage/store.go
Closes: https://github.com/onflow/flow-evm-gateway/issues/6
Functionality to retrieve EVM logs.
______
> Implement the `eth_getLogs` JSON-RPC endpoint

- scripts/run.sh
> network env var

- scripts/run.sh
> fix script

- .github/workflows/ci.yml
- Makefile
- go.mod
- integration/e2e_test.go
- integration/go.mod
- integration/helpers.go
- models/transaction_test.go
- services/ingestion/engine.go
- services/ingestion/engine_test.go
- services/logs/filter.go
- services/logs/filter_test.go
- services/requester/requester.go
Various fixes for test failures and build errors.
______
> Fix tests and build errors

- config/config.go
Reverts onflow/flow-evm-gateway#97
> Revert "Populate `COAKey` config value"

- scripts/run.sh
> Bootstrap previewnet

- api/api.go
- integration/e2e_test.go
- integration/helpers.go
- services/requester/cadence/get_code.cdc
- services/requester/requester.go
Closes: https://github.com/onflow/flow-evm-gateway/issues/109
This endpoint can be used to fetch the deployed code at a given address.
______
> Implement the `eth_getCode` JSON-RPC endpoint

- storage/pebble/accounts.go
- storage/pebble/blocks.go
- storage/pebble/receipts.go
- storage/pebble/storage.go
- storage/pebble/transactions.go
Closes: #116 
This PR adds batching to make multiple storage operations atomic. 
______
> Batch database operations

- README.md
- bootstrap/bootstrap.go
- config/config.go
- services/requester/requester.go
Support configuring logs to define log level and "format"
______
> Configuration for logs

- api/server.go
Change request / response values to be included as values in logs not JSON
> Request response value logging

- api/server.go
> Log bugfix values

- api/api.go
- api/filter.go
- api/pull.go
- api/pull_test.go
- bootstrap/bootstrap.go
- config/config.go
- integration/e2e_test.go
- integration/helpers.go
- models/engine.go
- storage/pebble/blocks.go
> Pulling API and filter management

- services/traces/downloader.go
Remove validation of value, because it's accessing non-public data.
______
> Remove check of non-public data

- go.mod
- go.sum
- tests/go.mod
- tests/go.sum
> Update flow-go to v0.35.12

- api/api.go
- storage/pebble/storage.go
This addresses a weird edge case where data returned is being modified by someone. Confirmed it fixes the issue but follow-up discovery will still be done.
> Return storage copy of data

- cmd/main/main.go
Wait for the sigint signal in main routine
> Wait for sigint signal

- metrics/collector.go
> Bugfix metric balance initialization

- config/config.go
> Validate gas price in config

- tests/e2e-network/e2e_test.js
Traverse blockchain test will go through each block from the provided height and check parent block recursively.
> Improve network test with blockchain traverse

- bootstrap/bootstrap.go
- services/ingestion/engine.go
- services/replayer/blocks_provider_test.go
- storage/pebble/blocks.go
- storage/pebble/storage_test.go
> Use batch to init blocks

- api/api.go
- api/debug.go
- api/pull.go
- api/stream.go
- api/utils.go
- api/wallet.go
- eth/types/types.go
- eth/types/types_test.go
- services/requester/requester.go
- tests/web3js/eth_deploy_contract_and_interact_test.js
Closes: https://github.com/onflow/flow-evm-gateway/issues/655
This is a requirement for `ERC-4337`.
______
> Support `ethapi.StateOverride` argument in relevant JSON-RPC endpoints

- services/replayer/blocks_provider.go
> [DO NOT MERGE] replay fix for coinbase change

- bootstrap/bootstrap.go
- services/ingestion/engine_test.go
- services/replayer/blocks_provider_test.go
- storage/pebble/db.go
- storage/pebble/storage.go
- storage/pebble/storage_test.go
- storage/register_delta_test.go
This will help with the next step of using a component builder for the DB component
______
> Seperate creating and closing pebbleDB from storage

- cmd/run/cmd.go
This code will go away entirely soon. I just added a `sync.Once` for now
______
> Fix closing channel twice

- api/utils.go
- services/requester/requester.go
- tests/web3js/build_evm_state_test.js
- tests/web3js/debug_traces_test.js
- tests/web3js/eth_deploy_contract_and_interact_test.js
Reverts onflow/flow-evm-gateway#671
there are reports of tx failing with out of gas since this change. I suspect this change is related
> Revert "Improve gas estimation logic for `eth_estimateGas`"

- tests/web3js/eth_logs_filtering_test.js
> Use proper variable in E2E test file for logs filtering

- bootstrap/bootstrap.go
- cmd/run/cmd.go
- config/config.go
This builds on https://github.com/onflow/flow-evm-gateway/pull/728 by making the new PoC feature configurable with a CLI flag
> Make PoC configurable

- bootstrap/bootstrap.go
Co-authored-by: Peter Argue <89119817+peterargue@users.noreply.github.com>Closes: #???
______
> Update cadence/flow-go/flow-go-sdk/flow-emulator dependencies

- services/requester/requester.go
Previously this Header time was only created during startup, so it never got updated. This makes the EVM GW think that we're not yet in Pectra:
```bash
curl -XPOST 'https://testnet.evm.nodes.onflow.org' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x04f8c982022101800183016b1e94fe847d8bebe46799fce83eb52f38ef4b907996a680848129fc1cc0f85ef85c82022194313af46a48eeb56d200fae0edb741628255d379f0101a0f354c695f1a6fe9bc7655aa220bbc51a6c000a4221efb5d2e848f85918353524a0693de7bd731004910396bc7753ad13e11b90a350fb84128fda6d6439584836d880a0bdade120008921fd57b6d6999e983c84e0a8efdfb3bb282c80886b05e8b1fc3ea074c4362fd383323f7efc166ebe1ebc869c8909d97f8a8d6414b03a020a60d92b"],"id":2}' | jq
```
```json
{
"jsonrpc": "2.0",
"id": 2,
"error": { …
```
> Create `ValidationOptions` for each tx submission

- services/ingestion/block_tracking_subscriber.go
Follow up on: https://github.com/onflow/flow-evm-gateway/issues/841
Give blocks a chance to become sealed before calling `NotifyBlock`.
Soft finality ingests block headers that have a status of `BlockStatusFinalized`, but calling `NotifyBlock` might fail if the AN has not actually finished syncing all collections.
Hence, we keep a small queue of the incoming block headers, so that we can call  `NotifyBlock` on block N-5, where N is the height of the current block header. This will give enough time for the block to be sealed.
______
> Improve release frequency of signing keys for soft-finality
